// Generated by scripts/build-illustrations.mjs. Do not edit by hand.

export interface IllustrationPack {
  id: string;
  count: number;
}

/** A source colour that keeps its own CSS var: a light neutral surface or a chromatic fill. */
export interface IllustrationSourceTone {
  id: string;
  pack: string;
  kind: "surface" | "colour";
  source: string;
  l: number;
  c: number;
  h: number;
  /** How many elements use it across the pack, so the most used colour can lead. */
  uses: number;
}

export const ILLUSTRATION_PACKS: IllustrationPack[] = [
  {
    "id": "noodle",
    "count": 50
  },
  {
    "id": "ghost",
    "count": 20
  },
  {
    "id": "outline",
    "count": 99
  }
];

export const ILLUSTRATION_TONES: IllustrationSourceTone[] = [
  {
    "id": "noodle-c1",
    "pack": "noodle",
    "kind": "colour",
    "source": "#f953b2",
    "l": 0.6951,
    "c": 0.2204,
    "h": 349.07,
    "uses": 289
  },
  {
    "id": "noodle-c2",
    "pack": "noodle",
    "kind": "colour",
    "source": "#ef8e3f",
    "l": 0.7361,
    "c": 0.149,
    "h": 56.37,
    "uses": 5
  },
  {
    "id": "noodle-c3",
    "pack": "noodle",
    "kind": "colour",
    "source": "#f4d13b",
    "l": 0.8662,
    "c": 0.1616,
    "h": 95.21,
    "uses": 186
  },
  {
    "id": "noodle-c4",
    "pack": "noodle",
    "kind": "colour",
    "source": "#6966ed",
    "l": 0.5866,
    "c": 0.1977,
    "h": 279.38,
    "uses": 269
  },
  {
    "id": "noodle-s1",
    "pack": "noodle",
    "kind": "surface",
    "source": "#ffffff",
    "l": 1,
    "c": 0,
    "h": 89.88,
    "uses": 5
  },
  {
    "id": "ghost-s1",
    "pack": "ghost",
    "kind": "surface",
    "source": "#f4f4f4",
    "l": 0.9672,
    "c": 0,
    "h": 89.88,
    "uses": 13
  },
  {
    "id": "ghost-s2",
    "pack": "ghost",
    "kind": "surface",
    "source": "#ffffff",
    "l": 1,
    "c": 0,
    "h": 89.88,
    "uses": 106
  },
  {
    "id": "ghost-s3",
    "pack": "ghost",
    "kind": "surface",
    "source": "#edeeef",
    "l": 0.9486,
    "c": 0.0017,
    "h": 247.84,
    "uses": 163
  },
  {
    "id": "ghost-c1",
    "pack": "ghost",
    "kind": "colour",
    "source": "#ff6498",
    "l": 0.7136,
    "c": 0.1933,
    "h": 2.51,
    "uses": 126
  },
  {
    "id": "ghost-s4",
    "pack": "ghost",
    "kind": "surface",
    "source": "#e2e2e2",
    "l": 0.9128,
    "c": 0,
    "h": 89.88,
    "uses": 5
  },
  {
    "id": "ghost-s5",
    "pack": "ghost",
    "kind": "surface",
    "source": "#d6d6d6",
    "l": 0.8761,
    "c": 0,
    "h": 89.88,
    "uses": 15
  },
  {
    "id": "ghost-s6",
    "pack": "ghost",
    "kind": "surface",
    "source": "#d7e8f7",
    "l": 0.9229,
    "c": 0.0274,
    "h": 244.69,
    "uses": 1
  }
];
