import type { FontCategory } from "./google-fonts";
import type { FontMetrics } from "@/lib/font-metrics";

/** Where a family's webfont files come from. */
export type FontSource = "google" | "adobe" | "fontsource" | "foundry";

/**
 * A font the picker can offer, normalized across sources. Google families are
 * title-cased with spaces ("Proxima Nova"); Adobe families are the kit's CSS
 * slug ("proxima-nova"), so the two namespaces never collide and a family
 * string alone is enough to resolve its source. Fontsource families are
 * title-cased like Google's, but come from a fixed list that excludes every
 * Google name, so membership in that list settles it. Foundry families work
 * the same way, from a list of their own.
 */
export interface FontOption {
  family: string;
  /** Human-readable name for display. The family string stays the CSS identifier. */
  label: string;
  category: FontCategory;
  source: FontSource;
  /** Weights the source can actually serve, ascending. */
  weights: number[];
  /** Who drew it, for sources that gather families from many foundries. */
  foundry?: string;
}

/** One @font-face in an Adobe web project kit. */
export interface AdobeFace {
  family: string;
  weight: number;
  style: "normal" | "italic";
  /** Kit URL template, with a `{format}` placeholder and a query template. */
  src: string;
  primer: string;
}

/** The parsed contents of an Adobe Fonts web project. */
export interface AdobeKit {
  id: string;
  families: FontOption[];
  faces: AdobeFace[];
}

/** One curated Fontsource family, as generated by scripts/build-fontsource.mjs. */
export interface FontsourceFamily {
  /** npm package slug: `@fontsource/{id}`. */
  id: string;
  family: string;
  category: FontCategory;
  weights: number[];
  italic: boolean;
  /** Pinned npm version, so exported imports never shift under a design. */
  version: string;
  metrics: FontMetrics;
}

/** One file of a foundry family, at the weight and style it answers to. */
export interface FoundryFace {
  weight: number;
  style: "normal" | "italic";
  /** Path inside the package, to the foundry's own woff2. */
  path: string;
}

/** One family served from its foundry's repo, as generated by scripts/build-foundry-fonts.mjs. */
export interface FoundryFamily {
  family: string;
  foundry: string;
  category: FontCategory;
  /** jsDelivr package the files live in, pinned to a commit or version. */
  pkg: string;
  faces: FoundryFace[];
  /** The family's page at its foundry. */
  page: string;
  /** SPDX id of the licence the files are served under. */
  license: string;
  metrics: FontMetrics;
}
