import type { FontCategory } from "./google-fonts";
import type { FontMetrics } from "@/lib/font-metrics";

/** Where a family's webfont files come from. */
export type FontSource = "google" | "adobe" | "fontsource";

/**
 * A font the picker can offer, normalized across sources. Google families are
 * title-cased with spaces ("Proxima Nova"); Adobe families are the kit's CSS
 * slug ("proxima-nova"), so the two namespaces never collide and a family
 * string alone is enough to resolve its source. Fontsource families are
 * title-cased like Google's, but come from a fixed list that excludes every
 * Google name, so membership in that list settles it.
 */
export interface FontOption {
  family: string;
  /** Human-readable name for display. The family string stays the CSS identifier. */
  label: string;
  category: FontCategory;
  source: FontSource;
  /** Weights the source can actually serve, ascending. */
  weights: number[];
}

/** One @font-face in an Adobe web project kit. */
export interface AdobeFace {
  family: string;
  weight: number;
  style: "normal" | "italic";
  /** Kit URL template, with a `{format}` placeholder and a query template. */
  src: string;
  primer: string;
}

/** The parsed contents of an Adobe Fonts web project. */
export interface AdobeKit {
  id: string;
  families: FontOption[];
  faces: AdobeFace[];
}

/** One curated Fontsource family, as generated by scripts/build-fontsource.mjs. */
export interface FontsourceFamily {
  /** npm package slug: `@fontsource/{id}`. */
  id: string;
  family: string;
  category: FontCategory;
  weights: number[];
  italic: boolean;
  /** Pinned npm version, so exported imports never shift under a design. */
  version: string;
  metrics: FontMetrics;
}
